// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package mt_transferv1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_MultiTokenPacketData                  protoreflect.MessageDescriptor
	fd_MultiTokenPacketData_class            protoreflect.FieldDescriptor
	fd_MultiTokenPacketData_id               protoreflect.FieldDescriptor
	fd_MultiTokenPacketData_data             protoreflect.FieldDescriptor
	fd_MultiTokenPacketData_sender           protoreflect.FieldDescriptor
	fd_MultiTokenPacketData_receiver         protoreflect.FieldDescriptor
	fd_MultiTokenPacketData_away_from_origin protoreflect.FieldDescriptor
	fd_MultiTokenPacketData_dest_contract    protoreflect.FieldDescriptor
	fd_MultiTokenPacketData_amount           protoreflect.FieldDescriptor
)

func init() {
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_init()
	md_MultiTokenPacketData = File_tibc_apps_mt_transfer_v1_mt_transfer_proto.Messages().ByName("MultiTokenPacketData")
	fd_MultiTokenPacketData_class = md_MultiTokenPacketData.Fields().ByName("class")
	fd_MultiTokenPacketData_id = md_MultiTokenPacketData.Fields().ByName("id")
	fd_MultiTokenPacketData_data = md_MultiTokenPacketData.Fields().ByName("data")
	fd_MultiTokenPacketData_sender = md_MultiTokenPacketData.Fields().ByName("sender")
	fd_MultiTokenPacketData_receiver = md_MultiTokenPacketData.Fields().ByName("receiver")
	fd_MultiTokenPacketData_away_from_origin = md_MultiTokenPacketData.Fields().ByName("away_from_origin")
	fd_MultiTokenPacketData_dest_contract = md_MultiTokenPacketData.Fields().ByName("dest_contract")
	fd_MultiTokenPacketData_amount = md_MultiTokenPacketData.Fields().ByName("amount")
}

var _ protoreflect.Message = (*fastReflection_MultiTokenPacketData)(nil)

type fastReflection_MultiTokenPacketData MultiTokenPacketData

func (x *MultiTokenPacketData) ProtoReflect() protoreflect.Message {
	return (*fastReflection_MultiTokenPacketData)(x)
}

func (x *MultiTokenPacketData) slowProtoReflect() protoreflect.Message {
	mi := &file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_MultiTokenPacketData_messageType fastReflection_MultiTokenPacketData_messageType
var _ protoreflect.MessageType = fastReflection_MultiTokenPacketData_messageType{}

type fastReflection_MultiTokenPacketData_messageType struct{}

func (x fastReflection_MultiTokenPacketData_messageType) Zero() protoreflect.Message {
	return (*fastReflection_MultiTokenPacketData)(nil)
}
func (x fastReflection_MultiTokenPacketData_messageType) New() protoreflect.Message {
	return new(fastReflection_MultiTokenPacketData)
}
func (x fastReflection_MultiTokenPacketData_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_MultiTokenPacketData
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_MultiTokenPacketData) Descriptor() protoreflect.MessageDescriptor {
	return md_MultiTokenPacketData
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_MultiTokenPacketData) Type() protoreflect.MessageType {
	return _fastReflection_MultiTokenPacketData_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_MultiTokenPacketData) New() protoreflect.Message {
	return new(fastReflection_MultiTokenPacketData)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_MultiTokenPacketData) Interface() protoreflect.ProtoMessage {
	return (*MultiTokenPacketData)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_MultiTokenPacketData) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Class != "" {
		value := protoreflect.ValueOfString(x.Class)
		if !f(fd_MultiTokenPacketData_class, value) {
			return
		}
	}
	if x.Id != "" {
		value := protoreflect.ValueOfString(x.Id)
		if !f(fd_MultiTokenPacketData_id, value) {
			return
		}
	}
	if len(x.Data) != 0 {
		value := protoreflect.ValueOfBytes(x.Data)
		if !f(fd_MultiTokenPacketData_data, value) {
			return
		}
	}
	if x.Sender != "" {
		value := protoreflect.ValueOfString(x.Sender)
		if !f(fd_MultiTokenPacketData_sender, value) {
			return
		}
	}
	if x.Receiver != "" {
		value := protoreflect.ValueOfString(x.Receiver)
		if !f(fd_MultiTokenPacketData_receiver, value) {
			return
		}
	}
	if x.AwayFromOrigin != false {
		value := protoreflect.ValueOfBool(x.AwayFromOrigin)
		if !f(fd_MultiTokenPacketData_away_from_origin, value) {
			return
		}
	}
	if x.DestContract != "" {
		value := protoreflect.ValueOfString(x.DestContract)
		if !f(fd_MultiTokenPacketData_dest_contract, value) {
			return
		}
	}
	if x.Amount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Amount)
		if !f(fd_MultiTokenPacketData_amount, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_MultiTokenPacketData) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.class":
		return x.Class != ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.id":
		return x.Id != ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.data":
		return len(x.Data) != 0
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.sender":
		return x.Sender != ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.receiver":
		return x.Receiver != ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.away_from_origin":
		return x.AwayFromOrigin != false
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.dest_contract":
		return x.DestContract != ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.amount":
		return x.Amount != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.MultiTokenPacketData"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.MultiTokenPacketData does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MultiTokenPacketData) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.class":
		x.Class = ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.id":
		x.Id = ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.data":
		x.Data = nil
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.sender":
		x.Sender = ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.receiver":
		x.Receiver = ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.away_from_origin":
		x.AwayFromOrigin = false
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.dest_contract":
		x.DestContract = ""
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.amount":
		x.Amount = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.MultiTokenPacketData"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.MultiTokenPacketData does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_MultiTokenPacketData) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.class":
		value := x.Class
		return protoreflect.ValueOfString(value)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.id":
		value := x.Id
		return protoreflect.ValueOfString(value)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.data":
		value := x.Data
		return protoreflect.ValueOfBytes(value)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.sender":
		value := x.Sender
		return protoreflect.ValueOfString(value)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.receiver":
		value := x.Receiver
		return protoreflect.ValueOfString(value)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.away_from_origin":
		value := x.AwayFromOrigin
		return protoreflect.ValueOfBool(value)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.dest_contract":
		value := x.DestContract
		return protoreflect.ValueOfString(value)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.amount":
		value := x.Amount
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.MultiTokenPacketData"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.MultiTokenPacketData does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MultiTokenPacketData) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.class":
		x.Class = value.Interface().(string)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.id":
		x.Id = value.Interface().(string)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.data":
		x.Data = value.Bytes()
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.sender":
		x.Sender = value.Interface().(string)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.receiver":
		x.Receiver = value.Interface().(string)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.away_from_origin":
		x.AwayFromOrigin = value.Bool()
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.dest_contract":
		x.DestContract = value.Interface().(string)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.amount":
		x.Amount = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.MultiTokenPacketData"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.MultiTokenPacketData does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MultiTokenPacketData) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.class":
		panic(fmt.Errorf("field class of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.id":
		panic(fmt.Errorf("field id of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.data":
		panic(fmt.Errorf("field data of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.sender":
		panic(fmt.Errorf("field sender of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.receiver":
		panic(fmt.Errorf("field receiver of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.away_from_origin":
		panic(fmt.Errorf("field away_from_origin of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.dest_contract":
		panic(fmt.Errorf("field dest_contract of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.amount":
		panic(fmt.Errorf("field amount of message tibc.apps.mt_transfer.v1.MultiTokenPacketData is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.MultiTokenPacketData"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.MultiTokenPacketData does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_MultiTokenPacketData) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.class":
		return protoreflect.ValueOfString("")
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.id":
		return protoreflect.ValueOfString("")
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.data":
		return protoreflect.ValueOfBytes(nil)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.sender":
		return protoreflect.ValueOfString("")
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.receiver":
		return protoreflect.ValueOfString("")
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.away_from_origin":
		return protoreflect.ValueOfBool(false)
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.dest_contract":
		return protoreflect.ValueOfString("")
	case "tibc.apps.mt_transfer.v1.MultiTokenPacketData.amount":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.MultiTokenPacketData"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.MultiTokenPacketData does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_MultiTokenPacketData) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in tibc.apps.mt_transfer.v1.MultiTokenPacketData", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_MultiTokenPacketData) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MultiTokenPacketData) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_MultiTokenPacketData) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_MultiTokenPacketData) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*MultiTokenPacketData)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Class)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Id)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Data)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Sender)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Receiver)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.AwayFromOrigin {
			n += 2
		}
		l = len(x.DestContract)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Amount != 0 {
			n += 1 + runtime.Sov(uint64(x.Amount))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*MultiTokenPacketData)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Amount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Amount))
			i--
			dAtA[i] = 0x40
		}
		if len(x.DestContract) > 0 {
			i -= len(x.DestContract)
			copy(dAtA[i:], x.DestContract)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DestContract)))
			i--
			dAtA[i] = 0x3a
		}
		if x.AwayFromOrigin {
			i--
			if x.AwayFromOrigin {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x30
		}
		if len(x.Receiver) > 0 {
			i -= len(x.Receiver)
			copy(dAtA[i:], x.Receiver)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Receiver)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Sender) > 0 {
			i -= len(x.Sender)
			copy(dAtA[i:], x.Sender)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Sender)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Data) > 0 {
			i -= len(x.Data)
			copy(dAtA[i:], x.Data)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Data)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Id) > 0 {
			i -= len(x.Id)
			copy(dAtA[i:], x.Id)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Id)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Class) > 0 {
			i -= len(x.Class)
			copy(dAtA[i:], x.Class)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Class)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*MultiTokenPacketData)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MultiTokenPacketData: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MultiTokenPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Class", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Class = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Id = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Data = append(x.Data[:0], dAtA[iNdEx:postIndex]...)
				if x.Data == nil {
					x.Data = []byte{}
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Sender = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Receiver = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AwayFromOrigin", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.AwayFromOrigin = bool(v != 0)
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DestContract", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DestContract = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
				}
				x.Amount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Amount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_ClassTrace            protoreflect.MessageDescriptor
	fd_ClassTrace_path       protoreflect.FieldDescriptor
	fd_ClassTrace_base_class protoreflect.FieldDescriptor
)

func init() {
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_init()
	md_ClassTrace = File_tibc_apps_mt_transfer_v1_mt_transfer_proto.Messages().ByName("ClassTrace")
	fd_ClassTrace_path = md_ClassTrace.Fields().ByName("path")
	fd_ClassTrace_base_class = md_ClassTrace.Fields().ByName("base_class")
}

var _ protoreflect.Message = (*fastReflection_ClassTrace)(nil)

type fastReflection_ClassTrace ClassTrace

func (x *ClassTrace) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ClassTrace)(x)
}

func (x *ClassTrace) slowProtoReflect() protoreflect.Message {
	mi := &file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ClassTrace_messageType fastReflection_ClassTrace_messageType
var _ protoreflect.MessageType = fastReflection_ClassTrace_messageType{}

type fastReflection_ClassTrace_messageType struct{}

func (x fastReflection_ClassTrace_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ClassTrace)(nil)
}
func (x fastReflection_ClassTrace_messageType) New() protoreflect.Message {
	return new(fastReflection_ClassTrace)
}
func (x fastReflection_ClassTrace_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ClassTrace
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ClassTrace) Descriptor() protoreflect.MessageDescriptor {
	return md_ClassTrace
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ClassTrace) Type() protoreflect.MessageType {
	return _fastReflection_ClassTrace_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ClassTrace) New() protoreflect.Message {
	return new(fastReflection_ClassTrace)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ClassTrace) Interface() protoreflect.ProtoMessage {
	return (*ClassTrace)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ClassTrace) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Path != "" {
		value := protoreflect.ValueOfString(x.Path)
		if !f(fd_ClassTrace_path, value) {
			return
		}
	}
	if x.BaseClass != "" {
		value := protoreflect.ValueOfString(x.BaseClass)
		if !f(fd_ClassTrace_base_class, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ClassTrace) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.ClassTrace.path":
		return x.Path != ""
	case "tibc.apps.mt_transfer.v1.ClassTrace.base_class":
		return x.BaseClass != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.ClassTrace"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.ClassTrace does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClassTrace) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.ClassTrace.path":
		x.Path = ""
	case "tibc.apps.mt_transfer.v1.ClassTrace.base_class":
		x.BaseClass = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.ClassTrace"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.ClassTrace does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ClassTrace) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "tibc.apps.mt_transfer.v1.ClassTrace.path":
		value := x.Path
		return protoreflect.ValueOfString(value)
	case "tibc.apps.mt_transfer.v1.ClassTrace.base_class":
		value := x.BaseClass
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.ClassTrace"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.ClassTrace does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClassTrace) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.ClassTrace.path":
		x.Path = value.Interface().(string)
	case "tibc.apps.mt_transfer.v1.ClassTrace.base_class":
		x.BaseClass = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.ClassTrace"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.ClassTrace does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClassTrace) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.ClassTrace.path":
		panic(fmt.Errorf("field path of message tibc.apps.mt_transfer.v1.ClassTrace is not mutable"))
	case "tibc.apps.mt_transfer.v1.ClassTrace.base_class":
		panic(fmt.Errorf("field base_class of message tibc.apps.mt_transfer.v1.ClassTrace is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.ClassTrace"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.ClassTrace does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ClassTrace) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "tibc.apps.mt_transfer.v1.ClassTrace.path":
		return protoreflect.ValueOfString("")
	case "tibc.apps.mt_transfer.v1.ClassTrace.base_class":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tibc.apps.mt_transfer.v1.ClassTrace"))
		}
		panic(fmt.Errorf("message tibc.apps.mt_transfer.v1.ClassTrace does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ClassTrace) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in tibc.apps.mt_transfer.v1.ClassTrace", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ClassTrace) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClassTrace) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ClassTrace) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ClassTrace) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ClassTrace)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Path)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.BaseClass)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ClassTrace)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.BaseClass) > 0 {
			i -= len(x.BaseClass)
			copy(dAtA[i:], x.BaseClass)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.BaseClass)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Path) > 0 {
			i -= len(x.Path)
			copy(dAtA[i:], x.Path)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Path)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ClassTrace)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ClassTrace: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ClassTrace: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Path = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BaseClass", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.BaseClass = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: tibc/apps/mt_transfer/v1/mt_transfer.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiTokenPacketData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the class to which the Mt to be transferred belongs
	Class string `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	// the mt id
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// the address defined by MT outside the chain
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// the mt sender
	Sender string `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	// the mt receiver
	Receiver string `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// identify whether it is far away from the source chain
	AwayFromOrigin bool `protobuf:"varint,6,opt,name=away_from_origin,json=awayFromOrigin,proto3" json:"away_from_origin,omitempty"`
	// the destination contract address to receive the nft
	DestContract string `protobuf:"bytes,7,opt,name=dest_contract,json=destContract,proto3" json:"dest_contract,omitempty"`
	// the amount defined by MT outside the chain
	Amount uint64 `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MultiTokenPacketData) Reset() {
	*x = MultiTokenPacketData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiTokenPacketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTokenPacketData) ProtoMessage() {}

// Deprecated: Use MultiTokenPacketData.ProtoReflect.Descriptor instead.
func (*MultiTokenPacketData) Descriptor() ([]byte, []int) {
	return file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *MultiTokenPacketData) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *MultiTokenPacketData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MultiTokenPacketData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MultiTokenPacketData) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MultiTokenPacketData) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *MultiTokenPacketData) GetAwayFromOrigin() bool {
	if x != nil {
		return x.AwayFromOrigin
	}
	return false
}

func (x *MultiTokenPacketData) GetDestContract() string {
	if x != nil {
		return x.DestContract
	}
	return ""
}

func (x *MultiTokenPacketData) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// ClassTrace contains the base class for Multi Token and the
// source tracing information path.
type ClassTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// path defines the chain of sourceChain/destChain
	// identifiers used for tracing the source of the Non fungible token.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// base class of the relayed non fungible token.
	BaseClass string `protobuf:"bytes,2,opt,name=base_class,json=baseClass,proto3" json:"base_class,omitempty"`
}

func (x *ClassTrace) Reset() {
	*x = ClassTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassTrace) ProtoMessage() {}

// Deprecated: Use ClassTrace.ProtoReflect.Descriptor instead.
func (*ClassTrace) Descriptor() ([]byte, []int) {
	return file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *ClassTrace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ClassTrace) GetBaseClass() string {
	if x != nil {
		return x.BaseClass
	}
	return ""
}

var File_tibc_apps_mt_transfer_v1_mt_transfer_proto protoreflect.FileDescriptor

var file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x74, 0x69, 0x62, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6d, 0x74, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x74, 0x69,
	0x62, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x6d, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0xeb, 0x01, 0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x28, 0x0a,
	0x10, 0x61, 0x77, 0x61, 0x79, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x61, 0x77, 0x61, 0x79, 0x46, 0x72, 0x6f,
	0x6d, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x64, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0xf7, 0x01, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69,
	0x62, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x6d, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x4d, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x61, 0x6e, 0x6a, 0x69, 0x65, 0x61, 0x69, 0x2f,
	0x74, 0x69, 0x62, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x69, 0x62, 0x63,
	0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6d, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x54, 0x41, 0x4d, 0xaa, 0x02, 0x17, 0x54, 0x69, 0x62, 0x63, 0x2e,
	0x41, 0x70, 0x70, 0x73, 0x2e, 0x4d, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x17, 0x54, 0x69, 0x62, 0x63, 0x5c, 0x41, 0x70, 0x70, 0x73, 0x5c, 0x4d,
	0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x23, 0x54,
	0x69, 0x62, 0x63, 0x5c, 0x41, 0x70, 0x70, 0x73, 0x5c, 0x4d, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x1a, 0x54, 0x69, 0x62, 0x63, 0x3a, 0x3a, 0x41, 0x70, 0x70, 0x73, 0x3a,
	0x3a, 0x4d, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescOnce sync.Once
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescData = file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDesc
)

func file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescGZIP() []byte {
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescOnce.Do(func() {
		file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescData)
	})
	return file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDescData
}

var file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tibc_apps_mt_transfer_v1_mt_transfer_proto_goTypes = []interface{}{
	(*MultiTokenPacketData)(nil), // 0: tibc.apps.mt_transfer.v1.MultiTokenPacketData
	(*ClassTrace)(nil),           // 1: tibc.apps.mt_transfer.v1.ClassTrace
}
var file_tibc_apps_mt_transfer_v1_mt_transfer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tibc_apps_mt_transfer_v1_mt_transfer_proto_init() }
func file_tibc_apps_mt_transfer_v1_mt_transfer_proto_init() {
	if File_tibc_apps_mt_transfer_v1_mt_transfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiTokenPacketData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tibc_apps_mt_transfer_v1_mt_transfer_proto_goTypes,
		DependencyIndexes: file_tibc_apps_mt_transfer_v1_mt_transfer_proto_depIdxs,
		MessageInfos:      file_tibc_apps_mt_transfer_v1_mt_transfer_proto_msgTypes,
	}.Build()
	File_tibc_apps_mt_transfer_v1_mt_transfer_proto = out.File
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_rawDesc = nil
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_goTypes = nil
	file_tibc_apps_mt_transfer_v1_mt_transfer_proto_depIdxs = nil
}
